// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppUpdate: typeof import('./src/components/app-update/index.vue')['default']
    ElProgress: typeof import('element-plus/es')['ElProgress']
  }
}

export { }
